[tool.poetry]
name = "davidbviana"
version = "0.1.0"
description = ""
authors = ["David Viana <me@davidviana.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
